module.exports = {
  semi: true,
  singleQuote: true,
  arrowParens: "avoid",
  trailingComma: "none",
  endOfLine: "auto",
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  bracketSpacing: true,
  jsxBracketSameLine: false,
  arrowParens: "avoid",
  proseWrap: "preserve",
  htmlWhitespaceSensitivity: "css",
  overrides: [
    {
      files: "*.js",
      options: {
        parser: "babel",
        singleQuote: false,
        trailingComma: "all",
        printWidth: 80,
        tabWidth: 2,
        useTabs: false,
        bracketSpacing: true,
        jsxBracketSameLine: false,
        arrowParens: "avoid",
        proseWrap: "preserve",
        htmlWhitespaceSensitivity: "css",
      },
    },
    {
      files: "*.ts",
      options: {
        parser: "typescript",
        singleQuote: false,
        trailingComma: "all",
        printWidth: 80,
        tabWidth: 2,
        useTabs: false,
        bracketSpacing: true,
        jsxBracketSameLine: false,
        arrowParens: "avoid",
        proseWrap: "preserve",
        htmlWhitespaceSensitivity: "css",
      },
    },
    {
      files: "*.tsx",
      options: {
        parser: "typescript",
        singleQuote: false,
        trailingComma: "all",
        printWidth: 80,
        tabWidth: 2,
        useTabs: false,
        bracketSpacing: true,
        jsxBracketSameLine: false,
        arrowParens: "avoid",
        proseWrap: "preserve",
        htmlWhitespaceSensitivity: "css",
      },
    },
    {
      files: "*.md",
      options: {
        parser: "markdown",
        singleQuote: false,
        trailingComma: "all",
        printWidth: 80,
        tabWidth: 2,
        useTabs: false,
        bracketSpacing: true,
        jsxBracketSameLine: false,
        arrowParens: "avoid",
        proseWrap: "preserve",
        htmlWhitespaceSensitivity: "css",
      },
    },
    {
      files: "*.json",
      options: {
        parser: "json",
        singleQuote: false,
        trailingComma: "all",
        printWidth: 80,
        tabWidth: 2,
        useTabs: false,
        bracketSpacing: true,
        jsxBracketSameLine: false,
        arrowParens: "avoid",
        proseWrap: "preserve",
        htmlWhitespaceSensitivity: "css",
      },
    },
    {
      files: "*.scss",
      options: {
        parser: "scss",
        singleQuote: false,
        trailingComma: "all",
        printWidth: 80,
        tabWidth: 2,
        useTabs: false,
        bracketSpacing: true,
        jsxBracketSameLine: false,
        arrowParens: "avoid",
        proseWrap: "preserve",
        htmlWhitespaceSensitivity: "css",
      },
    },
    {
      files: "*.css",
      options: {
        parser: "css",
        singleQuote: false,
        trailingComma: "all",
        printWidth: 80,
        tabWidth: 2,
        useTabs: false,
        bracketSpacing: true,
        jsxBracketSameLine: false,
        arrowParens: "avoid",
        proseWrap: "preserve",
        htmlWhitespaceSensitivity: "css",
      },
    },
    {
      files: "*.html",
      options: {
        parser: "html",
        singleQuote: false,
        trailingComma: "all",
        printWidth: 80,
        tabWidth: 2,
        useTabs: false,
        bracketSpacing: true,
        jsxBracketSameLine: false,
        arrowParens: "avoid",
        proseWrap: "preserve",
        htmlWhitespaceSensitivity: "css",
      },
    },
  ],
};
