export const GET_PURCHASES = "GET_PURCHASES";
export const GET_PURCHASES_SUCCESS = "GET_PURCHASES_SUCCESS";
export const GET_PURCHASES_FAILURE = "GET_PURCHASES_FAILURE";

export const RESET_PURCHASES = "RESET_PURCHASES";
