export const ADD_CARD = "ADD_CARD";
export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";
export const ADD_CARD_FAILURE = "ADD_CARD_FAILURE";

export const GET_CARDS = "GET_CARD";
export const GET_CARDS_SUCCESS = "GET_CARD_SUCCESS";
export const GET_CARDS_FAILURE = "GET_CARD_FAILURE";
