export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_CREATE = "USER_CREATE";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAILURE = "USER_CREATE_FAILURE";

export const USER_GET_ADDRESS = "USER_GET_ADDRESS";
export const USER_GET_ADDRESS_SUCCESS = "USER_GET_ADDRESS_SUCCESS";
export const USER_GET_ADDRESS_FAILURE = "USER_GET_ADDRESS_FAILURE";

export const USER_RESET_STATUS = "USER_RESET_STATUS";
