export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const ADD_PAYMENT = "ADD_PAYMENT";
export const ADD_ADDRESS = "ADD_ADDRESS";

export const CONFIRM_PURCHASE = "CONFIRM_PURCHASE";
export const CONFIRM_PURCHASE_SUCCESS = "CONFIRM_PURCHASE_SUCCESS";
export const CONFIRM_PURCHASE_FAILURE = "CONFIRM_PURCHASE_FAILURE";

export const RESET_CART = "RESET_CART";
